eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8099/eureka"
server:
  port: 8089
spring:
  cloud:
    gateway:
      routes:
        -
          id: client-service
          predicates:
            - Path=/clientBank/**
          uri: "http://localhost:8084/"